# path to a directory with all packages
storage: ../build/local-registry/storage

auth:
  htpasswd:
    file: ./htpasswd

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m
    max_fails: 20
    fail_timeout: 2m
  yarn:
    url: https://registry.yarnpkg.com
    maxage: 60m
    max_fails: 20
    fail_timeout: 2m

packages:
  # for @paima packages, we never want to fallback to the npm registry
  # otherwise, the local version will get rejected because the npm registry has a package with the same version
  '@paima/*':
    # allow all users full access (since it's a local registry)
    access: $all
    publish: $all
    unpublish: $all

  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs # fallback to npmjs for non-paima package. This is needed for transitive dependencies to work

# log settings
log:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true # set offline to true to allow publish offline
