import { getBackendUri, getBatcherUri } from '../state.js';
import createClient from 'openapi-fetch';
import type { Client } from 'openapi-fetch';

// generated by openapi-typescript
import type { paths as PaimaNodePaths } from './paima-node-rest-schema.d.js';
export type { paths as PaimaNodePaths } from './paima-node-rest-schema.d.js';
// import type { paths as PaimaNodePaths } from './paima-batcher-rest-schema';
// export type { paths as PaimaNodePaths } from './paima-batcher-rest-schema';

export function getPaimaNodeRestClient(): Client<PaimaNodePaths> {
  return createClient<PaimaNodePaths>({ baseUrl: getBackendUri() });
}

// export function getPaimaBatcherRestClient(): Client<paths> {
//   return createClient<paths>({ baseUrl: getBatcherUri() });
// }
