import { insertDynamicExtension, registerDynamicChainDataExtension } from '@paima/db';
import type { SQLUpdate } from '@paima/db';
import type { TChainDataExtensionErc721Config, TChainDataExtensionGenericConfig } from './types.js';
import { CdeEntryTypeName, type CdeDynamicEvmPrimitiveDatum } from './types.js';
import {
  ChainDataExtensionType,
  DYNAMIC_PRIMITIVE_NAME_SEPARATOR,
  GlobalConfig,
  caip2PrefixFor,
} from '@paima/utils';

// We omit storing the name from the config because it's dynamically generated
// on the db insert as the primary key of the row. We can then recover it from
// the row when needed.
type StoredConfig<T> = Omit<T, 'name'> & { network: string };

export default async function processDatum(
  cdeDatum: CdeDynamicEvmPrimitiveDatum,
  _inPresync: boolean
): Promise<SQLUpdate[]> {
  let type;
  let config;

  // the numeric id is generated by the insert query.
  const baseName = `${cdeDatum.cdeName}${DYNAMIC_PRIMITIVE_NAME_SEPARATOR}`;
  switch (cdeDatum.payload.targetConfig.type) {
    case CdeEntryTypeName.ERC721:
      type = ChainDataExtensionType.ERC721;

      const erc721Config: StoredConfig<TChainDataExtensionErc721Config> = {
        ...cdeDatum.payload.targetConfig,
        contractAddress: cdeDatum.payload.contractAddress,
        startBlockHeight: cdeDatum.blockNumber,
        network: cdeDatum.network,
      };

      config = erc721Config;
      break;

    case CdeEntryTypeName.Generic:
      type = ChainDataExtensionType.Generic;

      const genericConfig: StoredConfig<TChainDataExtensionGenericConfig> = {
        ...cdeDatum.payload.targetConfig,
        contractAddress: cdeDatum.payload.contractAddress,
        startBlockHeight: cdeDatum.blockNumber,
        network: cdeDatum.network,
      };

      config = genericConfig;
      break;
    default:
      // This shouldn't really happen, but for some reason using the assertNever
      // idiom does not work.
      throw new Error('Unsupported dynamic primitive target');
  }

  const configs = await GlobalConfig.getInstance();
  const updateList: SQLUpdate[] = [
    [
      registerDynamicChainDataExtension,
      {
        base_name: baseName,
        cde_type: type,
        cde_caip2: caip2PrefixFor(configs[cdeDatum.network]),
        start_blockheight: cdeDatum.blockNumber,
        scheduled_prefix: config.scheduledPrefix,
      },
    ],
    [
      insertDynamicExtension,
      {
        base_name: baseName,
        parent_name: cdeDatum.cdeName,
        config: config,
      },
    ],
  ];

  return updateList;
}
