name = "micro/inverse-whirlpool"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'micro/inverse-whirlpool'"

[repository]
user = "micro"
project = "inverse-whirlpool"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"

[[dependencies]]
name = "aiken-lang/sparse-merkle-tree"
version = "main"
source = "github"
