name = "paima/inverse-whirlpool"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project Cardano inverse projection"

[repository]
user = "PaimaStudios"
project = "paima-engine"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"

[[dependencies]]
name = "aiken-lang/sparse-merkle-tree"
version = "main"
source = "github"
