version: '3.7'

services:

  paima-batcher-db:
    image: postgres:14
    container_name: paima-batcher-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_LOGGING: "true"
      PGPORT: ${BATCHER_DB_PORT}
    volumes:
      - ./db/migrations/up.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p ${BATCHER_DB_PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    expose:
      - "${BATCHER_DB_PORT}"
    ports:
      - "${BATCHER_DB_PORT}:${BATCHER_DB_PORT}"
    command: -p ${BATCHER_DB_PORT}

  paima-batcher:
    build:
      context: .
      target: production-build-stage
      dockerfile: Dockerfile
    container_name: paima-batcher
    ports:
      - '${BATCHER_PORT}:${BATCHER_PORT}'
    volumes:
      - ../.env.${NODE_ENV:-production}:/app/.env.${NODE_ENV:-production}
    restart: 'unless-stopped'
    links:
      - paima-batcher-db
    depends_on:
      - paima-batcher-db
    env_file:
      - ../.env.${NODE_ENV:-production}

volumes:
  data:
    driver: local