# compose file for booting a temporary Postgres node for use with pgtyped
services:
  database:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./migrations/up.sql:/docker-entrypoint-initdb.d/up.sql"
    healthcheck:
      # Use pg_isready to check postgres is running.
      test: pg_isready -U postgres -p 5432
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s
      start_interval: 1s
    ports:
      - "54322:5432"
