export enum ConfigPrimitiveType {
  Generic = 'generic',
  ERC20 = 'erc20',
  ERC20Deposit = 'erc20-deposit',
  ERC721 = 'erc721',
  ERC6551Registry = 'erc6551-registry',
  ERC1155 = 'erc1155',
  CardanoDelegation = 'cardano-stake-delegation',
  CardanoProjectedNFT = 'cardano-projected-nft',
  CardanoDelayedAsset = 'cardano-delayed-asset',
  CardanoTransfer = 'cardano-transfer',
  CardanoMintBurn = 'cardano-mint-burn',
  MinaEventGeneric = 'mina-event-generic',
  MinaActionGeneric = 'mina-action-generic',
  DynamicEvmPrimitive = 'dynamic-evm-primitive',
  MidnightContractState = 'midnight-contract-state',
}
