import type { EndpointTypes } from "../../shared/routes";
import type { ErrorShape } from "../../shared/errors";
import type { AxiosError, AxiosResponse } from "axios";
import type { Routes } from "../../shared/routes";
export type { RelationFilter, RelationFilterType, Pagination, UtxoPointer, } from "../../shared/models/common";
export * from "../../shared/routes";
export * from "../../shared/errors";
export type { EndpointTypes } from "../../shared/routes";
export type { ErrorShape } from "../../shared/errors";
export declare function query<T extends Routes>(urlBase: string, route: T, data: EndpointTypes[T]["input"]): Promise<EndpointTypes[T]["response"]>;
export declare function getErrorResponse(err: AxiosError<ErrorShape, unknown>): AxiosResponse<ErrorShape, unknown>;
