name: CI
on:
  push:
    branches:
      - 'master'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install deps
        run: npm ci
      - name: Lint affected
        run: npm run lint
      - name: Test affected
        run: npx nx affected -t test
      - name: Build affected
        run: npm run build
